// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZee8_u2GeWJt6TUGeaa9mlZEErg_JqnQ',
    appId: '1:123119442853:web:0dab050122b752a6b7664c',
    messagingSenderId: '123119442853',
    projectId: 'raselicthub',
    authDomain: 'raselicthub.firebaseapp.com',
    storageBucket: 'raselicthub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcpoxxa8hKfAReU0fSDhZnB5HNqBvYtPM',
    appId: '1:123119442853:android:4df65986c27e6ce7b7664c',
    messagingSenderId: '123119442853',
    projectId: 'raselicthub',
    storageBucket: 'raselicthub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL9UM0rrGnTvDF0arFRNxGu_5rdPM6tpY',
    appId: '1:123119442853:ios:bbb2e525765e8679b7664c',
    messagingSenderId: '123119442853',
    projectId: 'raselicthub',
    storageBucket: 'raselicthub.firebasestorage.app',
    iosBundleId: 'com.example.raselIctApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL9UM0rrGnTvDF0arFRNxGu_5rdPM6tpY',
    appId: '1:123119442853:ios:bbb2e525765e8679b7664c',
    messagingSenderId: '123119442853',
    projectId: 'raselicthub',
    storageBucket: 'raselicthub.firebasestorage.app',
    iosBundleId: 'com.example.raselIctApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZee8_u2GeWJt6TUGeaa9mlZEErg_JqnQ',
    appId: '1:123119442853:web:03086e04d28f3106b7664c',
    messagingSenderId: '123119442853',
    projectId: 'raselicthub',
    authDomain: 'raselicthub.firebaseapp.com',
    storageBucket: 'raselicthub.firebasestorage.app',
  );
}
